config/routes.rb
Blog::Application.routes.draw do

  devise_for :users

  root :to => 'posts#index'
  get '/posts/new',           :controller => :posts,         :action => :new,           :as => "new_post"
  get '/posts',               :controller => :posts,         :action => :index,         :as => "posts"
  post '/posts',               :controller => :posts,         :action => :create
  get '/posts/:id',           :controller => :posts,         :action => :show,          :as => "post" 
  get '/posts/edit/:id',     :controller => :posts,          :action => :edit,          :as => "edit_post"
  put '/posts/:id',           :controller => :posts,         :action => :update,         :as => "update"
  delete '/posts/:id',        :controller => :posts,         :action => :destroy        

  get '/posts/:id/comments/new',           :controller => :comments,         :action => :new,           :as => "new_comment"
  get '/posts/:id',                        :controller => :comments,         :action => :index,           :as => "index_comment"
  post '/posts/:id',                       :controller => :comments,         :action => :create
  delete '/posts/:id/comments/:idcomment', :controller => :comments,         :action => :destroy,        :as => "delete_comment"    
  get '/posts/:id/comments/edit/:idcomment', :controller => :comments,       :action => :edit,          :as => "edit_comment"
  put '/posts/:id/comments/:idcomment',                          :controller => :comments,       :action => :update,        :as => "update_comment"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
    
      
    validates_presence_of :post_id, :author, :body
    validates_length_of :body, :maximum => 450

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, :dependent => :destroy
    belongs_to :user
    
    validates_presence_of :title, :body
    validates_length_of :title, :maximum => 25
    validates_length_of :body, :maximum => 450
    
    validates_uniqueness_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user! , :except => [:new, :create]

  def new
       @post = Post.find(params[:id])
  end
  
  def create      
      @post = Post.find(params[:id])
      if user_signed_in?  # Utilisateur loggé, on place/fusionne le champ author avec l'adresse email de l'utilisateur
       @comment = @post.comments.create!(params[:comment].merge(:author => current_user.email))
      else  # Pas loggé c'est donc un anonyme
       @comment = @post.comments.create!(params[:comment].merge(:author => "Anonymous"))
      end
      
      redirect_to post_path(@post.id), notice: 'Comment was successfully created'
      rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique#, ActiveRecord::Validation
        redirect_to new_comment_path(@post.id), notice: 'Body can not be blank or Body too long'
  end
  
  def destroy
      @post = Post.find(params[:id])
      @comment = @post.comments.find(params[:idcomment])
      if current_user.email == @comment.author or current_user.admin? # Utilisateur correct
        @comment.destroy
        redirect_to post_path(@post.id), notice: 'Comment successfuly destroyed'
      else # Utilisateur non loggué / Annoyme
        redirect_to post_path(@post.id), notice: 'Access Denied'
      end
  end
  
  def edit
      @post = Post.find(params[:id])
      @comment = @post.comments.find(params[:idcomment])
      if current_user.email == @comment.author or current_user.admin? # Utilisateur correct
      else
              redirect_to post_path(@post.id), notice: 'Access Denied'
      end
  end
  
  def update  
    @post = Post.find(params[:id])
    @comment = @post.comments.find(params[:idcomment])
    @comment.update_attributes!(params[:comment])
    #render :text => params.inspect
    redirect_to post_path(@post.id), notice: 'Comment was successfully updated.'
    #if params[:comment][:body].nil?
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique, ActiveRecord::Validation
           redirect_to edit_comment_path(@post, @comment), notice: 'Body can not be blank, or Title or Body too long'
    #else
    #end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  #before_filter :authorized_user, :only => :destroy
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
	  format.js # new.js.erb
    end
  end
  
  def create
    current_user.posts.create!(params[:post])
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique, ActiveRecord::Validation
        respond_to do |format|
            format.html { redirect_to new_post_path, notice: 'Title can not be blank, Body can not be blank, or Title alrealy exists or Title or Body too long' }
            format.json { render json: @post.errors, status: :unprocessable_entity }

        end
    else
        respond_to do |format|
            format.html { redirect_to posts_path, notice: 'Post was successfully created.' } # rake routes pour voir la correspondance #@post = post(@post.id)
            format.json { render json: @post, status: :created, location: @post }
            #format.js
        end    
            #render :text => params.inspect
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    post = Post.find(params[:id])
    if current_user.id == post.user_id or current_user.admin
        post.destroy
        redirect_to posts_path, notice: 'Post successfully destroyed'
    else
        redirect_to posts_path, notice: 'Access Denied'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    if current_user.id == @post.user_id or current_user.admin == true
    else
        redirect_to posts_path, notice: 'Access Deniedaaa'
    end
        
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update_attributes!(params[:post])
    redirect_to post_path(@post), notice: 'Post was successfully updated.'
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique, ActiveRecord::Validation
           redirect_to edit_post_path(@post), notice: 'Title can not be blank, Body can not be blank, or Title alrealy exists or Title or Body too long'
  end
  
 #   private  
 #   def authorized_user
 #     #@post = current_user.posts.find_by_id(params[:id])
 #     redirect_to posts_path, notice: 'Access Denied' if current_user.posts.find_by_id(params[:id]).nil?
 #   end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>
<p class="msgflash" style="color : green"> <%= flash[:notice] %></p>

<%= form_tag(update_comment_path(@post.id, @comment.id), :method => "put", :id => 'edit_comment') do %>
  <p class="title"><%= label_tag(:comment_author, 'Author') %><br/>
  <%= text_field_tag('comment[author]', @comment.author, :disabled => true) %></p>
  <p class="body"><%= label_tag(:comment_body, 'Body') %><br/>
  <%= text_area_tag('comment[body]', @comment.body) %></p>
  <div class="actionc">
  <div class="boutoncreate"><%= submit_tag("Update Comment") %></div>
<% end %>

<%= link_to 'Back', post_path(@post.id), { :method => 'get', :class => "buttonback", :title => "back" }%>
</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>
<p class="msgflash" style="color : green"> <%= flash[:notice] %></p>

<%= form_tag(post_path(@post.id), :method => "post", :id => 'new_comment') do %>
  <p class="title"><%= label_tag(:comment_author, 'Author') %><br/>
  <%= text_field_tag('comment[author]') %></p>
  <p class="body"><%= label_tag(:comment_body, 'Body') %><br/>
  <%= text_area_tag('comment[body]') %></p>
  <div class="actionc">
  <div class="boutoncreate"><%= submit_tag("Create Comment") %></div>

<% end %>

<%= link_to 'Back', post_path(@post.id), { :method => 'get', :class => "buttonback", :title => "back" }%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tag %>   
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="container">
      <header>

        <%= image_tag("blog1.jpg", :alt => "Blog img", :width => "300", :height => "150", :class => "round") %>
        <nav class="round">   
          <ul>          
            <li><%= link_to "Home", root_path %></li> |
            <% if user_signed_in? %>
              <li><%= current_user.email %></li> |
              <li><%= link_to "Settings", edit_registration_path(current_user) %></li> |
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li> |
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>
    </div>
  </body>
</html>
 

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create.js.erb
$("body ul tbody").append("<%= escape_javascript(@posts.title) %>");
$("form#new_post").remove();
$("a[href='<%= new_post_path %>']").fadeIn();

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<p style="color : green"> <%= flash[:notice] %></p>
<p style="color : red"> <%= flash[:error] %></p>
<%= form_tag(update_path(@post), :method => "put", :id => 'edit_post') do %>
  <p class="title"><%= label_tag(:post_title, 'Title') %><br/>
  <%= text_field_tag('post[title]', @post.title) %></p>
  <p class="body"><%= label_tag(:post_body, 'Body') %><br/>
  <%= text_area_tag('post[body]', @post.body) %></p>
  <div class="action">
    <div class="boutoncreate"><%= submit_tag("Update Post") %></div>
    <% end %>
    <%= link_to 'Back', root_path, { :method => 'get', :class => "buttonback", :title => "back" }%>
  </div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<p style="color : green"> <%= flash[:notice] %></p>

<ul id='posts'>
  <% @posts.each do |post| %>
  <div class='post'>
    <li id='post_<%= post.id %>'>        
        <h2 class='post-title'><%= link_to h(post.title), post, :method => 'get' %></h2> 
	    <div class='post-etat'>
		    <div class='post-info'>posté le <%= post.created_at %></div>
	            <div class='post-nagivation'>        
                    <label class='droite'><%= link_to "Delete this Post", post, { :method => 'delete', :class => 'supprimerp', :title => 'Delete Post' } %></label>
                    <label class='droite'><%= link_to "Edit this Post", edit_post_path(post.id), { :method => 'get', :class => 'editerp', :title => 'Edit Post' } %></label>
                    <label class='droite'><%= link_to "Show this Post", post, { :method => 'get', :class => 'afficherp', :title => 'Show Post' }%></label>
                </div>
         </div>
         <div class='post-body'><%= post.body %></div>
	     <div class='post-commentaire'>
            <% nb_comment = Comment.find_all_by_post_id(post.id).size%>
            <%=nb_comment%> commentaire<%if nb_comment>1%>s<%end%><i></label>
	     </div>					

    </li>
  </div>
  <% end %>
</ul>
<%= link_to "Create a new Post", new_post_path, :class => "createnewpost round" %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>
<p class="msgflash" style="color : green"> <%= flash[:notice] %></p>
<p style="color : red"> <%= flash[:error] %></p>
<%= form_tag(posts_path, :method => "post", :id => 'new_post') do %>
  <p class="title"><%= label_tag(:post_title, 'Title') %><br/>
  <%= text_field_tag('post[title]') %></p>
  <p class="body"><%= label_tag(:post_body, 'Body') %><br/>
  <%= text_area_tag('post[body]') %></p>
<div class="action">
<div class="boutoncreate"><%= submit_tag("Create Post") %></div>

<% end %>

<%= link_to 'Back', root_path, { :method => 'get', :class => "buttonback", :title => "back" }%>
</div>

app/views/posts/new.js.erb
$("form").remove();
$("a[href='<%= new_post_path %>']").after("<%= escape_javascript(render 'form') %>");
$("form#new_post").attr("data-remote", true);
$("a[href='<%= new_post_path %>']").fadeOut();

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<p style="color : green"> <%= flash[:notice] %></p>

<div class="postview">  
  <p>
  <b><h2 class="post-showtitle"><%= label_tag(:post_title, 'Title : ') %><%= @post.title %></h2></b>
  </p>
  <div class='barre'></div>
  <p>
  <b><div class="post-showbody"><h3 class="post-showbodycolor"><%= label_tag(:post_body, 'Body :') %></h3><%= @post.body %></div></b>

  </p>
</div>

<ul id='comments'>
  <% @post.comments.each do |comment| %>
    <div class="comment">
    <li id='comment_<%= comment.id %>'>
        <h2 class="comment-title"><%= comment.author %></h2> 
            <div class='barre'></div>
            <div class="comment-nagivation"> 
                <label class="droite"><%= link_to "Delete this Comment", delete_comment_path(@post.id, comment.id), { :method => 'delete', :class => "supprimerc", :title => "Delete Comment" } %></label>
                <label class="droite"><%= link_to "Edit this Comment", edit_comment_path(@post.id, comment.id), { :method => 'get', :class => "editc", :title => "Edit Comment" } %></label>
            </div>
        <div class="comment-body"><%= comment.body %></div>
    </li>
    </div>
  <% end %>
</ul>
<div class="actioncomment">
    <div class="boutoncreate"><%= button_to 'Create a new Comment', new_comment_path(@post.id), :method=>"get" %></div>
    <%= link_to 'Back', root_path, { :method => 'get', :class => "buttonback", :title => "back" }%>
</div>